[db]
uri = "postgres://rumba:rumba@127.0.0.1:5432/mdn"

[server]
port = 8000

[auth]
issuer_url = "http://localhost:4321"
redirect_url = "http://localhost:8000/users/fxa/login/callback/"
scopes = "openid profile email profile:subscriptions"
auth_cookie_name = "auth-cookie"
auth_cookie_secure = false
client_id="TEST_CLIENT_ID"
client_secret="TEST_CLIENT_SECRET"
auth_cookie_key = "DUwIFZuUYzRhHPlhOm6DwTHSDUSyR5SyvZHIeHdx4DIanxm5/GD/4dqXROLvn5vMofOYUq37HhhivjCyMCWP4w=="

[application]
document_base_url = "http://localhost:4321"
subscriptions_limit_watched_items = 3
subscriptions_limit_collections = 5

[search]
url = "ignored"
cache_max_age = 43200