[db]
uri = "postgres://postgres:mdn@127.0.0.1/mdn "

[server]
port = 8000

[auth]
issuer_url = "https://accounts.stage.mozaws.net"
redirect_url = "http://localhost:8000/users/fxa/login/callback/"
scopes = "openid profile email profile:subscriptions"
auth_cookie_name = "auth-cookie"
auth_cookie_secure = false
auth_cookie_key = "DUwIFZuUYzRhHPlhOm6DwTHSDUSyR5SyvZHIeHdx4DIanxm5/GD/4dqXROLvn5vMofOYUq37HhhivjCyMCWP4w=="

[search]
url = "http://elastic:9200"
cache_max_age = 43200