[package]
name = "rumba"
version = "0.0.1"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "rumba"
path = "src/main.rs"

[dependencies]
thiserror = "1.0"
anyhow = "1.0"

actix-web = "4"
actix-http = "3"
actix-rt = "2"
actix-identity = "0.4"

diesel = { version = "1.4", features = ["postgres", "uuid", "r2d2", "chrono", "serde_json"] }
diesel_migrations = "1.4"
r2d2 = "0.8"

openidconnect = "2"
reqwest = { version = "0.11", features = ["blocking", "json"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

log = "0.4"
env_logger = "0.9"
config = "0.13"

uuid = { version = "1", features = ["serde", "v4"] }
chrono = "0.4"
url = "2"

once_cell = "1"