env: prod
namespace: mdn-prod

service:
  ssl_certificate_arn: arn:aws:acm:us-west-2:178589013767:certificate/6cd2746f-26e7-491f-95ba-4972b1aa5879

deployment:
  replicas: 2
  updateStrategy:
    type: RollingUpdate

  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 2
      memory: 512Mi

settings:
  server__port: 8000
  server__host: "0.0.0.0"
  auth__issuer_url: "https://accounts.firefox.com"
  auth__redirect_url: "https://developer.mozilla.org/users/fxa/login/callback/"
  auth__scopes: "openid profile email profile:subscriptions"
  auth__auth_cookie_name: "auth-cookie"
  auth__auth_cookie_secure: true
  auth__client_id: 720bc80adfa6988d

  application__document_base_url: "https://developer.mozilla.org"
  application__notifications_update_base_url: "https://updates.developer.mozilla.org/notifications"
  application__subscriptions_limit_watched_items: 3
  application__subscriptions_limit_collections: 5

  search__cache_max_age: 43200
  search__query_max_length: 200

  metrics__statsd_label: "rumba_prod"
