name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MDN_SETTINGS: .settings.test.toml

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: rumba
          POSTGRES_PASSWORD: rumba
          POSTGRES_DB: mdn
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.75.0
          override: true
          components: rustfmt, clippy
      - name: FMT
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --all --all-features -- -D warnings
      - name: Build
        run: cargo build --all --all-features --verbose
      - name: Run tests
        run: RUST_BACKTRACE=1 RUST_LOG=rumba:info MDN_SETTINGS=.settings.test.toml cargo test --all -- --test-threads=1 --nocapture
